name: ACL Lab
on: push

jobs:
  lab:
    runs-on: ubuntu-latest
    name: Memory Output
    steps:
      - uses: actions/checkout@v3 
      - name: run the action
        id: memory_output
        uses: ./
      - name: output the memory
        run: |
          echo ${{ steps.memory_outputs.memory }}
